name: e_commerce_alwalla
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  chopper: ^3.0.6
  provider: ^4.3.2+3
  get: ^3.22.2
  flutter_html: ^1.1.1
  json_serializable: ^3.5.1
  shared_preferences: ^0.5.12+4
  equatable: ^1.2.5
  http: ^0.12.2
  flutter_svg: ^0.19.1
  string_validator: ^0.1.4
  cached_network_image: ^2.4.1
  transparent_image: ^1.0.0
  permission_handler: ^5.0.1+1
  mask_text_input_formatter: ^1.1.0
  auto_size_text: ^2.1.0
  rounded_loading_button: ^1.0.17
  pull_to_refresh: ^1.6.3
  content_placeholder: ^0.1.0
  path_provider: ^1.6.24
  google_sign_in: ^4.5.6
  sign_in_with_apple: ^2.5.4
  flushbar: ^1.10.4
  smooth_star_rating: 1.1.1
  page_transition: ^1.1.7+3
  slide_item: ^1.0.8
  im_stepper: ^0.1.2+8
  font_awesome_flutter: ^8.10.1
  flutter_xlider: 3.4.0
  carousel_pro: ^1.0.0
  flutter_staggered_grid_view: ^0.3.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.7
  chopper_generator: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 800

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 800

flutter_intl:
  enabled: true
