name: e_commerce_alwalla
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: 4.3.2+2
  flutter_bloc: 6.0.5
  json_serializable: ^3.5.0
  shared_preferences: ^0.5.12
  equatable: ^1.2.5
  http: ^0.12.2
  flutter_svg: ^0.19.0
  string_validator: ^0.1.4
  cached_network_image: ^2.3.2+1
  transparent_image: ^1.0.0
  permission_handler: ^5.0.1+1
  mask_text_input_formatter: ^1.1.0
  auto_size_text: ^2.1.0
  rounded_loading_button: ^1.0.13
  pull_to_refresh: ^1.6.2
  content_placeholder: ^0.1.0
  path_provider: ^1.6.18
  google_sign_in: ^4.5.4
  sign_in_with_apple: ^2.5.2
  flushbar: ^1.10.4
  smooth_star_rating: 1.1.1
  page_transition: ^1.1.6
  slide_item: 1.0.7
  im_stepper: ^0.1.2+5
  font_awesome_flutter: 8.8.1
  flutter_xlider: 3.4.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 800

flutter_intl:
  enabled: true
